<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ZTR.Models\ZTR.Models.csproj" />
    <ProjectReference Include="..\ZTR.Common\ZTR.Common.csproj" />
    <ProjectReference Include="..\ZTR.HAL\ZTR.HAL.csproj" />
    <ProjectReference Include="..\ZTR.Intelligence\ZTR.Intelligence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="System.Management" Version="10.0.11" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ZTR.Api.Tests" />
  </ItemGroup>

</Project>
