<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZTR.Models\ZTR.Models.csproj" />
    <ProjectReference Include="..\ZTR.Common\ZTR.Common.csproj" />
    <ProjectReference Include="..\ZTR.HAL\ZTR.HAL.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>