name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: 'latest'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing workflow dispatch"
